### ISSUE TITLE
Link to Keyword Documentation

### ISSUE THREAD

**Issue by Tset-Noitamotua** [s4int/robotframework-BrowserMobProxyLibrary#2]
Is there a keyword documentation available?

Cheers
Tset

**Comment by s4int** [comment]
Here is link: [Keywords](https://rawgit.com/s4int/robotframework-BrowserMobProxyLibrary/master/doc/BrowserMobProxyLibrary.html)

Best,
Marcin

**Comment by s4int** [comment]
fixed

**Comment by Tset-Noitamotua** [comment]
Great! Thank you!

You might want to mention keyword documention in your [README.me](https://github.com/s4int/robotframework-BrowserMobProxyLibrary/blob/master/README.md)

**Comment by s4int** [comment]
@Tset-Noitamotua good idea. Thanks for this.
